### ISSUE TITLE
Login failure with No Access-Control-Allow-Origin error

### ISSUE THREAD

**Issue by tinshuksingh** [FINRAOS/herd-ui#2]
I am trying to login from herd-ui, getting _No Access-Control-Allow-Origin_ error.

![herd_login_failure](https://user-images.githubusercontent.com/20110386/36480339-f912392e-1731-11e8-9392-c9ca6a0b9b38.PNG)

- We tried to add a CORS filter in Tomcat's web.xml as given [here](https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html), however it didn't help.

**Below is our application setup -**
- [herd-ui](https://github.com/FINRAOS/herd-ui) configured with 'ng server' with port 4222 is trying to communicate with [herd](https://github.com/FINRAOS/herd) app configured on tomcat server with port 8080.
- Is there a default username and password configured to login? If not, how can we configure it?

**Comment by kenisteward** [comment]
For your herd configuration, do you have it setup to accept basicAuthentication?

If not and you are just using TRUSTED_USER, you are not required to use basic auth in herd-ui and the app will understand the context of the users.

Also for your CORS filter, try this configuration:

```xml
<web-app>
        <!-- other properties left out for brevity -->
      <filter>
      <filter-name>CorsFilter</filter-name>
      <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
      <init-param>
         <param-name>cors.allowed.origins</param-name>
         <param-value>*</param-value>
      </init-param>

    <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>Content-Type,Authorization,Accept,Origin</param-value>
    </init-param>

      <init-param>
         <param-name>cors.allowed.methods</param-name>
         <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
      </init-param>
  </filter>
   <filter-mapping>
      <filter-name>CorsFilter</filter-name>
      <url-pattern>/*</url-pattern>
   </filter-mapping>
</web-app>
```

**Comment by kenisteward** [comment]
In a week or so we'll have the cloudformation set this up for you if you can wait.  Hopefully by the end of feb :)

**Comment by tinshuksingh** [comment]
@kenisteward 

Thank you very much for quick reply. We tried the configuration you shared and this worked for us.
Thanks again!!!

**Comment by manasguduri** [comment]
<img width="1440" alt="screen shot 2018-02-23 at 4 14 10 pm" src="https://user-images.githubusercontent.com/7077808/36617280-d2340b46-18b4-11e8-9761-4ceb01a0b892.png">

**Comment by manasguduri** [comment]
@tinshuksingh Can you be more clear on how you created the credentials for the Herd-UI login page. I tried editing the web.xml as @kenisteward suggested, but am not clear.

Please help!


Thanks,
Manas

**Comment by kenisteward** [comment]
@manasguduri 

If you are using our cloudformation setup, You do not require basic auth.  As long as basic auth is not setup, you don't require using the useBasicAuth setting and the app will properly get Trusted_User from HERD.

Key things:
Make sure CORS is setup as I suggested here.
Make sure to have useBasicAuth set to false

If you require basic auth on your instance:
You need to configure herd itself to have the credentials as users in it's tables.

**Comment by manasguduri** [comment]
@kenisteward Thanks for your response.

I have set the useBasicAuth to false and CORS is set up in /var/lib/tomcat8/webapps/herd-app/WEB-INF/web.xml

But, am still getting continuous errors as this. 
<img width="1440" alt="screen shot 2018-02-27 at 3 15 02 pm" src="https://user-images.githubusercontent.com/7077808/36754365-be3c2fd6-1bd6-11e8-8af8-cc30d8b888f5.png">

**Comment by kenisteward** [comment]
From that error this is still a cors issue. Please make sure your settings are as prescribed in this issue. 

If you could post your settings we can look at them

**Comment by manasguduri** [comment]
Is this correct? @kenisteward 

<web-app>
        
      <filter>
      <filter-name>CorsFilter</filter-name>
      <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
      <init-param>
         <param-name>cors.allowed.origins</param-name>
         <param-value>*</param-value>
      </init-param>

    <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>Content-Type,Authorization,Accept,Origin</param-value>
    </init-param>

      <init-param>
         <param-name>cors.allowed.methods</param-name>
         <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
      </init-param>
  </filter>
   <filter-mapping>
      <filter-name>CorsFilter</filter-name>
      <url-pattern>MY_INSTANCE_URL</url-pattern>
   </filter-mapping>
</web-app>

**Comment by manasguduri** [comment]
<web-app>
        
      <filter>
      <filter-name>CorsFilter</filter-name>
      <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
      <init-param>
         <param-name>cors.allowed.origins</param-name>
         <param-value>*</param-value>
      </init-param>

    <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>Content-Type,Authorization,Accept,Origin</param-value>
    </init-param>

      <init-param>
         <param-name>cors.allowed.methods</param-name>
         <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
      </init-param>
  </filter>
   <filter-mapping>
      <filter-name>CorsFilter</filter-name>
      <url-pattern>INSTANCE_ID:4200</url-pattern>
   </filter-mapping>
</web-app>

**Comment by manasguduri** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/7077808/36767232-a05ada54-1c07-11e8-9385-f22bf9df2357.png)

**Comment by tinshuksingh** [comment]
@manasguduri 

I added this filter in tomcat's web.xml file. 
File location: `tomcat8/conf/web.xml`

**Comment by kenisteward** [comment]
I would start with /* and then restrict as needed.  Also I don't believe port goes in the url-pattern based on the spec.
