### ISSUE TITLE
View Data Linage using Actions Bar -> Lineage 

### ISSUE THREAD

**Issue by simplyCode09489** [FINRAOS/herd-ui#22]
Hi, I wanted to explore the View Data Linage functionality using the  Actions Bar -> Lineage action, but i am having a hard time trying to figure out what data to load to view this. Is there a chance someone can please provide some sample data/REST calls to load some data which will enable this action ?

Thanks !

**Comment by nateiam** [comment]
Yes, that is a cool feature that we haven't documented well in our open source release in GitHub.

The way to populate the data for this is to use this REST endpoint:
http://finraos.github.io/herd/docs/latest/rest/index.html#!/Business_Object_Format/BusinessObjectFormat_updateBusinessObjectFormatParents

The idea is that when someone creates a Format, they can reference one or more other Formats of data they use when assembling data of their Format. This is then surfaced by the button you mention.

To experiment, you can either register some new Data Entities and Formats (aka BusinessObjectDefinitions and BusinessObjectFormat in REST language) and then use the Format Parents PUT endpoint --or-- you can find some of the sample objects created during your installation and point one to the other.

Let us know if you have any more questions! Also we are happy to get together and talk - it's always good to connect with others that are building data lakes and learn what we're all thinking and doing.

**Comment by simplyCode09489** [comment]
Thanks Nate for the information - much appreciated ! I was able to bring up the Linage View using the tips provided.

Just to confirm , the 1st 3 items in the Action Menu (Share, Save, Watch) are pending a future implementation ?

**Comment by kenisteward** [comment]
@simplyCode09489 Yup! those were put there just as a marker for things we'd like to come but may not necessarily stay.  Closing this as it seems the issue has been resolved.
