### ISSUE TITLE
How to associate Herd with Herd-UI?

### ISSUE THREAD

**Issue by manasguduri** [FINRAOS/herd-ui#3]
It is mentioned in the Wiki that "one can generically associate Herd-UI with Herd"

I am not able to understand how to connect the herd instance which is created using Cloud formation with the herd-ui code.

I tried installing angular cli and created a new project but unable to open angular project through port 4200 on the ec2 instance.

Please help!

Thanks,
Manas

**Comment by kenisteward** [comment]
@manasguduri 
Here is the configuration guide:
https://github.com/FINRAOS/herd-ui/wiki/Configuration-and-Test-Guide

Settings need to be changed in this file:
https://github.com/FINRAOS/herd-ui/blob/master/src/configuration.json
All you really need to do is set the restBaseUri or the basicAuthRestBaseUri when using basic auth.  You can technically avoid using the second if your base line of your sever is using basic auth but you have to remember in all cases to set useBasicAuth: true.

**Comment by manasguduri** [comment]
@kenisteward 
Thanks for the prompt response.

I have been following the link you mentioned, at first I installed Angular CLI on the Instance created by the cloudformation template, there is no configuration.json in the the ng project so later I created configuration.json as suggested in the Wiki. But, I still get the angular ui page, but not the herd-ui !

Waiting for reply!


Manas

"restBaseUri": "https://my.herd-instance.com/herd-app/rest",
  "basicAuthRestBaseUri": "https://my.herd-instance-using-basic-auth.com:8443/herd-app/rest",
  "supportEmail": "support@my-support.com",

**Comment by kenisteward** [comment]
That is a splash page with an outdated logo :)

If you could open f12 and show what errors are propagating that would be helpful.

If the app is not loading 99 percent of the time it or the herd instance is not configured properly. 

If you herd instance is on a different domain, see issue #2 for details on setting up the timcat filter

**Comment by kenisteward** [comment]
Also if you aren't using basic auth and want to use the base TRUSTED_USER, useBasicAuth should be false.

**Comment by manasguduri** [comment]
@kenisteward 
Hi, I went through my configuration.json and clear few errors and now I am getting an error - Google Analytics has not been configured for this deployment. Either trackAnalytics has not been set in the configuration.json or ga.trackingId has not been provided in the configuration. 

I have provided my Google tracking ID, but am still getting this error.

Given my configuration.json file:

![image](https://user-images.githubusercontent.com/7077808/36615949-126e545a-18b0-11e8-80b0-e49154afb7b8.png)

**Comment by kenisteward** [comment]
that's a warning not an error.  That's because trackAnalytics is set to false.  If you have a ga account and want to use it then you need to set trackAnalytics: true before it will use the ga functions.  

Otherwise your app is working right?

**Comment by manasguduri** [comment]
I have set that to true, n no change.

My app is not working too, am still getting a blank page !

Thanks,
Manas

**Comment by kenisteward** [comment]
The blank page would be that the app can't talk to your ec2 instance most likely due to cors

**Comment by kenisteward** [comment]
Take a screen shot of your console errors when you are getting the blank page.

**Comment by manasguduri** [comment]
@kenisteward 
I got the login page now, but I got the same error as #2, I will do the edits you suggested in the previous issue and update you.

Thanks for your fast response.

Manas

**Comment by manasguduri** [comment]
@kenisteward 
I am not clear like how to set the the username and password still. Can you be bit ore clear on that?

Thanks,
Manas

**Comment by manasguduri** [comment]
<img width="1440" alt="screen shot 2018-02-23 at 4 14 10 pm" src="https://user-images.githubusercontent.com/7077808/36617299-e29efc52-18b4-11e8-8995-65f0a64a5886.png">

**Comment by kenisteward** [comment]
@manasguduri That is not an error.  It is a warning from the browser.  It won't have anything with the atual request.

Please send a picture of the actual error that you are listing.  

From what it sounds like your url is just incorrect though.

**Comment by manasguduri** [comment]
@kenisteward I don't have any other error other than that warning. If my URL is wrong it doesn't even open the page I guess. But, how to create the credentials is my question?

Thanks,
Manas

**Comment by kusid** [comment]
The `restBaseUri` setting in your config file looks a little off to me unless you configured it like that in Herd, the default is: `"restBaseUri": "https://my.herd-instance.com/herd-app/rest"`. Notice that it ends with a `rest` and not a `herd-ui`.

**Comment by manasguduri** [comment]
@kusid 
No, the restbaseUri doesn't have herd-ui in the end it has rest as you mentioned the default.

**Comment by kenisteward** [comment]
This is still saying that the options request is refused which is a cors setting issue.

**Comment by tinshuksingh** [comment]
@manasguduri 

- If you are not making use of authentication then below is the configuration.json file:
		**{
		  "restBaseUri": "http://ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com:8080/herd-app/rest",
		  "supportEmail": "support@my-support.com",
		  "brandHeader": "Herd",
		  "brandMotto": "Locate and understand data available in Herd!",
		  "docTitlePrefix": "Herd-UI",
		  "useBasicAuth": false,
		  "alertDelayInSeconds": 10,
		  "trackAnalytics": false,
		  "ga": {
			"key": "PWD for UserName Encryption",
			"iv": "IV for UserName Encryption",
			"trackingId": "Enter Tacking ID Here"
		  },
		  "roles": {
			"editDataEntityDescription": {
			},
			"editDataEntityColumns": {
			},
			"editDataEntityTags": {
			},
			"data_objects": {
			}
		  }
		}**

- To resolve CORS issue, add below filter to `web.xml` file of tomcat server (**tomcat8/conf/web.xml**).
<web-app>

	
	<filter>
		<filter-name>CorsFilter</filter-name>
		<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
		<init-param>
			<param-name>cors.allowed.origins</param-name>
			<param-value>*</param-value>
		</init-param>

		<init-param>
			<param-name>cors.allowed.headers</param-name>
			<param-value>Content-Type,Authorization,Accept,Origin</param-value>
		</init-param>

		<init-param>
			<param-name>cors.allowed.methods</param-name>
			<param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>CorsFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

</web-app>

**Comment by kenisteward** [comment]
@manasguduri can we close this?
